spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:7777/mydatabase
    username: postgres
    password: asif
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#eureka:
  #client:
    #serviceUrl:
      #defaultZone: http://localhost:8080/eureka
server:
  port: 9090